
[extensions]
"omni.services.transport.server.http" = {}
"omni.services.livestream.nvcf" = {}
"omni.kit.livestream.webrtc" = {}
"omni.kit.window.core" = {}

[livestream]
enabled = true
web_port = 8222
stream_port = 49001

[renderer]
raytracing.enabled = true
rtx.enabled = true

[app]
window.width = 1920
window.height = 1080
